import React from 'react'

export const metadata = {
  title: "Lookvisa - Login",
  description: "Generated by create next app",
};

const layout = ({ children }) => {
  return (
    <>
      {children}
    </>
  )
}

export default layout