import React from 'react'

export const metadata = {
    title: "Forget Password",
    description: "Generated by create next app",
  };
  
const layout = ({children}) => {
  return (
    <>
    {children}
    </>
  )
}

export default layout